### ISSUE TITLE
Редизайн шапки 

### ISSUE THREAD

**Issue by vex2k** [srgg6701/auction-ruseasons#16]
Необходимо изменить дизайн шапки сделав его чуть менее аляповатым и адаптировать под мобильные системы. уменьшить высоту шапки что бы она не занимала треть экрана. возможно стоит пойти по пути расмуасена, когда для внутряков шапка уменьшается, эт просто иедя пока. 
Требования - картина остается в шапке или ее элементе, поиск съезжает вниз в полоску меню как в http://www.bruun-rasmussen.dk/index.do

Необхобимые, но возможно не все пункты меню из шапки:
 Магазин Аукцион Оценка Партнеры Правила Контакты
Сменить логотип в шапке на новый, он визуально выглядит так же как тут http://auction-ruseasons.ru/ только еще вензели сверху. Можно значительно уменьшить его в размерах. Под\справа от логотипа в 3 строки текст вида
магазин
антикварные сезоны
аукцион

Регистрацию и вход вынести так же как у расмунседа наверх, что бы они не занимали целый столбец. сделать кнопку "предложить предмет" или что то вроде ведущую на такую же страницу как и в оригинальном сайте так же убрать ее из отдельного столбца. куда разместить особых идей пока нет

**Comment by srgg6701** [comment]
Этот их логотип, конечно, это просто кирдык, кроме приступа тошноты никаких ощущений не вызывает :(

**Comment by vex2k** [comment]
не могу не согласиться. Может попробовать убедить сделать нормальнео что то минималистиченое типа как на расмусене или у них в фавиконке - без этих извратов с овалами и коронами с кучей мелких деталек? заказчица в пт вроде возвращается, могу пообщаться
