### ISSUE TITLE
Доработки аукциона

### ISSUE THREAD

**Issue by vex2k** [srgg6701/auction-ruseasons#18]
1) доработать форму поиска там пропуск между полем поиска и лупой так и остался. 

2) верстку товаров нужно подправить http://2013.auction-ruseasons.ru/%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD-%D0%B0%D0%BD%D1%82%D0%B8%D0%BA%D0%B2%D0%B0%D1%80%D0%B8%D0%B0%D1%82%D0%B0/raznoe 

3) что там с картинками - показывает белые поля? 

4) форму регистрации нужно подправить http://2013.auction-ruseasons.ru/component/auction2013/?layout=register  вид должен быть аналогичен http://auction-ruseasons.ru/register.php

5) нужно сделать форму подачи заявки предмета на торги точно как тут  http://auction-ruseasons.ru/index.php?a=28&b=136

6) результаты поиска вывод оформить так же как на оригинальном сайте: http://2013.auction-ruseasons.ru/component/search/?searchword=%D0%BB%D0%B8%D1%82%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%8F&searchphrase=all&Itemid=115 
http://auction-ruseasons.ru/index.php?a=19&b%5Bsearch_text%5D=%EB%E8%F2%EE%E3%F0%E0%F4%E8%FF

7) на мобильнике у меня показывается полная версия все время, нужно что бы отображалась мобильная. 

8) текст "© 2010 Антикварные Сезоны" на больших мониторах уезжает вправо, хотя должен оставаться на месте. 

9) убрать лишнюю линию фона видимую в выпадающем меню снизу

10) картинка в шапке на пиксель отступает от плашки меню снизу. нужно убрать отсутп

11) уточнение текст  "антикварные сезоны" кажется мне сплющенным по высоте, или так и было в psd?

**Comment by serge-serg** [comment]
1) доработать форму поиска там пропуск между полем поиска и лупой так и остался.

доработал

2) верстку товаров нужно подправить http://2013.auction-ruseasons.ru/%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD-%D0%B0%D0%BD%D1%82%D0%B8%D0%BA%D0%B2%D0%B0%D1%80%D0%B8%D0%B0%D1%82%D0%B0/raznoe

Если это насчёт съезжающего заголовка, то подправил

4) форму регистрации нужно подправить http://2013.auction-ruseasons.ru/component/auction2013/?layout=register вид должен быть аналогичен http://auction-ruseasons.ru/register.php

проверяй

5) нужно сделать форму подачи заявки предмета на торги точно как тут http://auction-ruseasons.ru/index.php?a=28&b=136

В прошлый раз там был другой контент. Проверяй как выглядит сейчас. Я поставил там кнопку как на других страницах. Или оставить разнопоматерную?

6) результаты поиска вывод оформить так же как на оригинальном сайте: http://2013.auction-ruseasons.ru/component/search/?searchword=%D0%BB%D0%B8%D1%82%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%8F&searchphrase=all&Itemid=115 
http://auction-ruseasons.ru/index.php?a=19&b%5Bsearch_text%5D=%EB%E8%F2%EE%E3%F0%E0%F4%E8%FF

Абсолютно новое требование

7) на мобильнике у меня показывается полная версия все время, нужно что бы отображалась мобильная.

Загрузи каноническую стр. плз: http://getbootstrap.com 
и сообщи, эту отображает, как мобильную?

8) текст "© 2010 Антикварные Сезоны" на больших мониторах уезжает вправо, хотя должен оставаться на месте.

Пофиксил

9) убрать лишнюю линию фона видимую в выпадающем меню снизу

Убрал

10) картинка в шапке на пиксель отступает от плашки меню снизу. нужно убрать отсутп

Убрал

11) уточнение текст "антикварные сезоны" кажется мне сплющенным по высоте, или так и было в psd?

У меня всё точно накладывается на подложку

**Comment by vex2k** [comment]
2) верстку товаров нужно подправить http://2013.auction-ruseasons.ru/%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD-%D0%B0%D0%BD%D1%82%D0%B8%D0%BA%D0%B2%D0%B0%D1%80%D0%B8%D0%B0%D1%82%D0%B0/raznoe

Если это насчёт съезжающего заголовка, то подправил, 

--нет, речь про ширину рабочей области с товарами - сейчас они слишком липнут друг к другу. справа большой пустой кусок остается. Понимаю что из за разных макетов, но надо пофиксить. Что с меня потом скажи.

6) результаты поиска вывод оформить так же как на оригинальном сайте: http://2013.auction-ruseasons.ru/component/search/?searchword=%D0%BB%D0%B8%D1%82%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%8F&searchphrase=all&Itemid=115 
http://auction-ruseasons.ru/index.php?a=19&b%5Bsearch_text%5D=%EB%E8%F2%EE%E3%F0%E0%F4%E8%FF

Абсолютно новое требование

--тем не менее нужно сделать вывод как в оригинальном сайте. Раз я профилонил и этот момент еще на момент создания магазина - записывай на мой счет что должен буду за эту доработку. 

7) на мобильнике у меня показывается полная версия все время, нужно что бы отображалась мобильная.

Загрузи каноническую стр. плз: http://getbootstrap.com 
и сообщи, эту отображает, как мобильную?

--показывает мобильную версию сайта

**Comment by serge-serg** [comment]
***Понимаю что из за разных макетов, но надо пофиксить. Что с меня потом скажи.
Так как пофиксить именно? На всю ширину растянуть или что? А если оно тебе опять не понравится? Может дизайнерша сделает картинку?
