### ISSUE TITLE
Баг: вывод 2х фотографий вместо 3х на ipad mini

### ISSUE THREAD

**Issue by vex2k** [srgg6701/auction-ruseasons#19]
![2](https://cloud.githubusercontent.com/assets/7836205/5180253/0e30538e-74a3-11e4-96b9-172a63a89a01.png)

НА малых разрешениях выводится по 2 картинки в ряду.
![image](https://cloud.githubusercontent.com/assets/7836205/5180329/c64b5040-74a3-11e4-824b-4089d64ceb50.jpeg)

**Comment by srgg6701** [comment]
Я думал это фича. В общем, сейчас вплоть до 1024px показывает в 3 ряда.
