### ISSUE TITLE
Выяснить, какие поля являются обязательными при импорте/добавлении/редактировании предметов

### ISSUE THREAD

**Issue by srgg6701** [srgg6701/auction-ruseasons#2]
Определить имена 3-х полей для цен и поля, обязательные для проверки.
См. отправленный по емэйлу .xlsx-файл.

**Comment by vex2k** [comment]
price1 price2 price3 . важное замечание - в очных торгах оценочная стоимость выдается в у.е. впрочем, наверное это легко решается просто правкой шаблона вывода. хотя конечно можно и валюту задать - смотри сам как разумнее и проще сделать.  в онлайн торгах и магазине цены только в рублях.
