### ISSUE TITLE
Баг сортировки предметов

### ISSUE THREAD

**Issue by vex2k** [srgg6701/auction-ruseasons#20]
При переходе по пагинации между страницми с предметами они выводятся вслучайном порядке постоянно меняя свое расположение. Затрудняет рабоут с сайтом и путает пользователей. Попробуй попререходить по этим 2м ссылкам(1 и 2я страницы в навигации соответственно ) http://2013.auction-ruseasons.ru/%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD-%D0%B0%D0%BD%D1%82%D0%B8%D0%BA%D0%B2%D0%B0%D1%80%D0%B8%D0%B0%D1%82%D0%B0/raznoe?start_page=1 http://2013.auction-ruseasons.ru/%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD-%D0%B0%D0%BD%D1%82%D0%B8%D0%BA%D0%B2%D0%B0%D1%80%D0%B8%D0%B0%D1%82%D0%B0/raznoe?start_page=2

на фото ниже одна и та же страница
![image](https://cloud.githubusercontent.com/assets/7836205/5180379/514380e6-74a4-11e4-8422-faef66e9d4eb.jpeg)
![default](https://cloud.githubusercontent.com/assets/7836205/5180380/53888dec-74a4-11e4-8e6f-59fb35bdd5e7.JPG)

**Comment by srgg6701** [comment]
Не вижу там никаких багов. Оно выводится вовсе не в случайном порядке, а по окончанию даты публикации. Картинки могут быть очень похожими, но это ни о чём не говорит. Единственный достоверный критерий - id id предметов в списке.
Вот адреса с выводом и запросов, и id id предметов:
http://2013.auction-ruseasons.ru/%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD-%D0%B0%D0%BD%D1%82%D0%B8%D0%BA%D0%B2%D0%B0%D1%80%D0%B8%D0%B0%D1%82%D0%B0/raznoe?start_page=1&qtest=1
http://2013.auction-ruseasons.ru/%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD-%D0%B0%D0%BD%D1%82%D0%B8%D0%BA%D0%B2%D0%B0%D1%80%D0%B8%D0%B0%D1%82%D0%B0/raznoe?start_page=2&qtest=1

**Comment by srgg6701** [comment]
Исправлено.

**Comment by vex2k** [comment]
по ссылке http://2013.auction-ruseasons.ru/%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD-%D0%B0%D0%BD%D1%82%D0%B8%D0%BA%D0%B2%D0%B0%D1%80%D0%B8%D0%B0%D1%82%D0%B0?pages_limit=60 предметы все равно прыгают.

**Comment by srgg6701** [comment]
Было то, что и в прошлый раз, только для ТОП-категорий. Исправил.
