### ISSUE TITLE
Вывести предметы из очных торгов на фронтенд включить их в поиск

### ISSUE THREAD

**Issue by vex2k** [srgg6701/auction-ruseasons#22]
На новом сайте вывести результаты очных торгов c 6 проведенных торогов: в таком виде: http://auction-ruseasons.ru/index.php?a=5&b=234&search=1&num_auction=%B96
- создать страницу под их вывод аналогичную этой http://auction-ruseasons.ru/index.php?a=ap&addon=extra_pages&page=page 

Поиск должен работать на все лоты, находящиеся на сайте (в т.ч. из прошедших очных торгов)

**Comment by srgg6701** [comment]
Проверяй. Только плз., добавьте сами всех - что прошли, что не прошли и т.д.

**Comment by vex2k** [comment]
там при нажатии на результаты торгов выкидывает на старый сайт. Куда добавлять лоты очных торгов и как их разделять по аукционам и нужно ли что бы для каждого аукциона была своя категория не пересекающаяся с другими очными торгами?
