### ISSUE TITLE
Съехала верстка футера 

### ISSUE THREAD

**Issue by vex2k** [srgg6701/auction-ruseasons#24]
нужно уменьшить шрифт текста в футере что бы на айпаде туда влазили следующие пункты меню:
-КОНТАКТЫ
- ВОПРОСЫ
- ДОСТАВКА И ОПЛАТА
- СПИСОК НЕПЛАТЕЛЬЩИКОВ
- ПАРТНЕРЫ

Сейчас как понимаю из за слишком  длинного текста оно на 2ю строку перескакивает
![3](https://cloud.githubusercontent.com/assets/7836205/5180608/d78daa80-74a6-11e4-806f-113ed742cdc1.JPG)

**Comment by srgg6701** [comment]
Картинку специально вверх ногами загрузили?

**Comment by vex2k** [comment]
Не, привет гитхабу который переворачивает картинки за каким то лядом. у меня они нормально смотрятся.

**Comment by srgg6701** [comment]
Там последнее меню - тестовое. Так и наз. - "test". Поэтому достаточно сделать следующее:
1. Скачать эту картинку.
2. Перевести в нормальную ориентацию.
3. Внимательно рассмотреть. Убедиться, что меню "test" там, действительно, есть.
4. Зайти в админку и отключить его (меню).
5. Испытать удовлетворение.
Ну, если вы считаете, что я всё это должен сделать, зайду, отключу сам.

**Comment by srgg6701** [comment]
Вижу, меня опередили.
