### ISSUE TITLE
Не работает навигация предыдущий\следующий предмет внутри карточек товаров

### ISSUE THREAD

**Issue by vex2k** [srgg6701/auction-ruseasons#26]
http://2013.auction-ruseasons.ru/%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD-%D0%B0%D0%BD%D1%82%D0%B8%D0%BA%D0%B2%D0%B0%D1%80%D0%B8%D0%B0%D1%82%D0%B0/raznoe/laquo-%D0%BD%D0%B0%D1%82%D1%8E%D1%80%D0%BC%D0%BE%D1%80%D1%82-c-%D0%B6%D0%B5%D0%BB%D1%82%D1%8B%D0%BC%D0%B8-%D1%80%D0%BE%D0%B7%D0%B0%D0%BC%D0%B8-raquo-detail

**Comment by srgg6701** [comment]
Кто-то залез в святая святых. Или опять сбой в Матрице.
