### ISSUE TITLE
Убрать разниу в названиях категории иколичества преметов в ней

### ISSUE THREAD

**Issue by vex2k** [srgg6701/auction-ruseasons#27]
http://auction-ruseasons.ru/category/310/%D0%9C%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD.html

и 

http://2013.auction-ruseasons.ru/%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD-%D0%B0%D0%BD%D1%82%D0%B8%D0%BA%D0%B2%D0%B0%D1%80%D0%B8%D0%B0%D1%82%D0%B0

**Comment by srgg6701** [comment]
т.е., сделать как на старом сайте?
