### ISSUE TITLE
не работает изменение количества товаров на страницу. все время отображается 15

### ISSUE THREAD

**Issue by vex2k** [srgg6701/auction-ruseasons#28]
http://2013.auction-ruseasons.ru/%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD-%D0%B0%D0%BD%D1%82%D0%B8%D0%BA%D0%B2%D0%B0%D1%80%D0%B8%D0%B0%D1%82%D0%B0/?pages_limit=30

**Comment by srgg6701** [comment]
Спасибо, что включили в админке кэш, а мне не сказали - целый день мучил себя. И даже хостеров пришлось. Теперь у нас стало больше одним местом, где нужно стелить соломку! :)
