### ISSUE TITLE
Выбор типа валюты в админке не меняет тип валюты во фронтенде

### ISSUE THREAD

**Issue by vex2k** [srgg6701/auction-ruseasons#33]
Выбор типа валюты в админке не меняет тип валюты во фронтенде

**Comment by srgg6701** [comment]
Конкретный пример товара со ссылкой, пожалуйста.

**Comment by vex2k** [comment]
http://2013.auction-ruseasons.ru/%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD-%D0%B0%D0%BD%D1%82%D0%B8%D0%BA%D0%B2%D0%B0%D1%80%D0%B8%D0%B0%D1%82%D0%B0/raznoe/%D0%B1%D1%83%D0%B1%D0%B5%D0%BD-laquo-%D0%BF%D0%B0%D1%80%D1%83%D1%81%D0%BD%D0%B8%D0%BA-%D0%B2-%D0%BC%D0%BE%D1%80%D0%B5-raquo-detail
