### ISSUE TITLE
Не рабьотает импорт из csv

### ISSUE THREAD

**Issue by vex2k** [srgg6701/auction-ruseasons#38]
при попытке импорта отправленного по почте файла вылазит ошибка  ! $isChild file: /home/a/auctionru/2013/public_html/administrator/components/com_virtuemart/models/product.php 
line: 1718

**Comment by srgg6701** [comment]
Сервер прерывает обработку больших скриптов. Нужно экспериментировать с объёмом импортируемых файлов.
