### ISSUE TITLE
Проверка остальных полей при импорте предметов

### ISSUE THREAD

**Issue by srgg6701** [srgg6701/auction-ruseasons#4]
Там есть ещё поля:
   auction_number
   lot_number
   contract_number
которые в настоящий момент не являются обязательными к заполнению при импорте предметов. Так и оставить или добавить проверку?

**Comment by vex2k** [comment]
auction_number - обязательное поле для очных аукционов lot_number насколько помню использовалось как id , contract_number обязательнео поле, должно быть уникальным - это номер контракта под которым сдали товар, два раза он повторяться не может.
