### ISSUE TITLE
Не работает проигрыватель картинок 

### ISSUE THREAD

**Issue by vex2k** [srgg6701/auction-ruseasons#41]
http://2013.auction-ruseasons.ru/%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD-%D0%B0%D0%BD%D1%82%D0%B8%D0%BA%D0%B2%D0%B0%D1%80%D0%B8%D0%B0%D1%82%D0%B0/%D0%BA%D0%BE%D0%BB%D0%BB%D0%B5%D0%BA%D1%86%D0%B8%D1%8F-%D0%B8%D0%B7-%D1%81%D0%BE%D0%B1%D1%80%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BA-%D0%B2-%D1%88%D0%B0%D1%82%D0%B8%D0%BB%D0%BE%D0%B2%D0%B0-detail

**Comment by srgg6701** [comment]
Я уже писал, что картинки должны загружаться в дир. preview, а не resized. Они там как оказываются?

**Comment by vex2k** [comment]
Они там оказываются например при создании предмета вручную скорее всего.

**Comment by srgg6701** [comment]
Проверяй. И сразу нужно проверить, нет ли там дублированных картинок. Т.е., когда к предмету прилагаются якобы разные, но на самом деле, просто копии одной и той же.
