### ISSUE TITLE
нет навигации по предметам вперед назад

### ISSUE THREAD

**Issue by vex2k** [srgg6701/auction-ruseasons#42]
http://2013.auction-ruseasons.ru/%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD-%D0%B0%D0%BD%D1%82%D0%B8%D0%BA%D0%B2%D0%B0%D1%80%D0%B8%D0%B0%D1%82%D0%B0/%D0%BA%D0%BE%D0%BB%D0%BB%D0%B5%D0%BA%D1%86%D0%B8%D1%8F-%D0%B8%D0%B7-%D1%81%D0%BE%D0%B1%D1%80%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BA-%D0%B2-%D1%88%D0%B0%D1%82%D0%B8%D0%BB%D0%BE%D0%B2%D0%B0-detail
нет навигации по предметам вперед назад

**Comment by srgg6701** [comment]
Проверяй сейчас.
