### ISSUE TITLE
Цена для магазина

### ISSUE THREAD

**Issue by srgg6701** [srgg6701/auction-ruseasons#7]
## 8) если предмет не продан, и в нем не прописана цена для магазина, то он исчезает из публичного доступа. - 

Имеется в виду поле "Конечная цена" в админке?

**Comment by vex2k** [comment]
вот поэтому я и говорил что лучше разнести цены для каждого из видов торгов магазина\онлайн торгов\авкциона. если бы это были отдельные поля подобные вопросы даже не могли бы возникнуть. Вообще ответ на вопросы - все предметы после окончания времени публикации исчезают из поля зрения. Т.е. вне зависимости от того была прописана цена для магазина или нет. После этого с ним вручную  работают администраторы. Может все же лучше завести отдельные поля для цен каждого из разделов (онлайн магазин очные) что бы избежать путаницы?
