### ISSUE TITLE
Шаг торгов

### ISSUE THREAD

**Issue by srgg6701** [srgg6701/auction-ruseasons#8]
## 11) размер ставок и шаг торгов можно посмотреть в инструкции к аукциону.

Шаг торгов остаётся постоянным для предмета, исходя из стартовой цены или изменяется динамически в соответствии с размером последней ставки?

**Comment by vex2k** [comment]
шаг торгов рассчитывается в соответствии в стаблицей которую нужно скопировать отсюда: http://auction-ruseasons.ru/index.php?a=28&b=148 стартовая цена предмета всегда будет вносится кратной шагу торгов администраторами.
